### ISSUE TITLE
OpenCTIApiClient.malware.list() returns inconsistent results with getAll=True parameter

### ISSUE THREAD

**Issue by Markus98** [OpenCTI-Platform/client-python#425] opened 2023-07-13 11:37 UTC
## Description
When using the `OpenCTIApiClient.malware.list()` method with parameters `getAll=True` and `customAttributes="id name aliases"`, the resulting list of entities varies in length inconsistently. It may be related to the large number of entities that is being fetched.

The same inconsistent behavior seems to happen even when `customAttributes` is not set.

## Environment

1. OS (where OpenCTI server runs): Official Docker Image
2. OpenCTI version: OpenCTI 5.8.7
3. Other environment details: -

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Running this script with the `OPENCTI_URL` and `OPENCTI_TOKEN` environment variables defined causes the inconsistent behavior.

```Python
from pycti import OpenCTIApiClient
import os

client = OpenCTIApiClient(url=os.environ.get("OPENCTI_URL"), token=os.environ.get("OPENCTI_TOKEN"))

for i in range(10):
    malware_entities = client.malware.list(
        customAttributes="id name aliases",
        getAll=True,
    )
    print(f"Fetched entities: {len(malware_entities)}")
```

## Expected Output

The number of fetched entities should be the same for each run of the `client.malware.list` method.

## Actual Output
The number of fetched entities is inconsistent:

Output:
```
INFO:pycti.entities:Listing Threat-Actors with filters null.
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjI5LCJtYWx3YXJlLS1iYmJlZWUxNy03MzJhLTUzMjctYWExNS05ZDI2ZjQ1NjQzYTkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzE0MDkyMywibWFsd2FyZS0tNzMwNzRkM2QtN2NlYy01M2NkLWJjM2ItYTI5NmZkYjMxNTI5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tMzRkNTVmMDMtMzBmNC01MzI3LWFlYTUtMDc0NTFiNDg1OTliIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDI1NCwibWFsd2FyZS0tYTZmOWY4MGUtNDkyNS01YWVkLTgzOGUtNGQ2N2NmMGM0NDhmIl0=
Fetched entities: 2500
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMjk4LCJtYWx3YXJlLS1jMGFkMjkxZS00YjYxLTViMTEtOGQzZC04YjdhOGZjYjViMDkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjI5LCJtYWx3YXJlLS03MDUwZDEwZC03NTBmLTU1ZTctYWZiOS00MGU3YmYwNDBlNmMiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDYzLCJtYWx3YXJlLS1iYmJlZWUxNy03MzJhLTUzMjctYWExNS05ZDI2ZjQ1NjQzYTkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzUyMzg1NiwibWFsd2FyZS0tN2U2NTU0N2ItMGNkNC01MWM1LTgyMDQtZDFlZjc1MmQxNWY2Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzE0MDkyMywibWFsd2FyZS0tYTc5MDgwYjMtOTRmMy01YmMzLTk1MTMtNDY3YzI0NDNmMDcxIl0=
INFO:pycti.entities:Listing Malwares after WzUuNjk3NzAxLCJtYWx3YXJlLS02MDNiYWVmNS03NmI4LTUzZWQtOThkZC02NGIxYmM1OTFlMWYiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tMDc4MjQ2NjQtOTc5My01ZTM3LTg2YjUtYTdlZjM5M2M5MDJjIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDI1NCwibWFsd2FyZS0tYTZmOWY4MGUtNDkyNS01YWVkLTgzOGUtNGQ2N2NmMGM0NDhmIl0=
Fetched entities: 4500
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMzAxNCwibWFsd2FyZS0tYzBhZDI5MWUtNGI2MS01YjExLThkM2QtOGI3YThmY2I1YjA5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDYzLCJtYWx3YXJlLS03MDUwZDEwZC03NTBmLTU1ZTctYWZiOS00MGU3YmYwNDBlNmMiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTAwNCwibWFsd2FyZS0tYTc5MDgwYjMtOTRmMy01YmMzLTk1MTMtNDY3YzI0NDNmMDcxIl0=
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tNmM3MGUzMWMtMTk0MC01ZWI3LWE3ODktMzk0OWU0MmM0NDgwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDMsIm1hbHdhcmUtLTFkN2Q0YThjLTE2NzYtNTkzNy05YTIwLWY0MjFiMGJhZmJhYyJd
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDMsIm1hbHdhcmUtLWM2M2UwOTRlLThkMGQtNWYzMS04NDNhLTA4YTg0YTJhODkxYyJd
Fetched entities: 3180
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMzA1LCJtYWx3YXJlLS1jMGFkMjkxZS00YjYxLTViMTEtOGQzZC04YjdhOGZjYjViMDkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjMzLCJtYWx3YXJlLS1iYmJlZWUxNy03MzJhLTUzMjctYWExNS05ZDI2ZjQ1NjQzYTkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDY2NiwibWFsd2FyZS0tYmJiZWVlMTctNzMyYS01MzI3LWFhMTUtOWQyNmY0NTY0M2E5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzUyMzkzMiwibWFsd2FyZS0tYzBhZDI5MWUtNGI2MS01YjExLThkM2QtOGI3YThmY2I1YjA5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTAwNCwibWFsd2FyZS0tYTc5MDgwYjMtOTRmMy01YmMzLTk1MTMtNDY3YzI0NDNmMDcxIl0=
INFO:pycti.entities:Listing Malwares after WzUuNjk3NzA1LCJtYWx3YXJlLS1hNmY5ZjgwZS00OTI1LTVhZWQtODM4ZS00ZDY3Y2YwYzQ0OGYiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
Fetched entities: 4000
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjMzLCJtYWx3YXJlLS1iYmJlZWUxNy03MzJhLTUzMjctYWExNS05ZDI2ZjQ1NjQzYTkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTA0LCJtYWx3YXJlLS03MzA3NGQzZC03Y2VjLTUzY2QtYmMzYi1hMjk2ZmRiMzE1MjkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tMzRkNTVmMDMtMzBmNC01MzI3LWFlYTUtMDc0NTFiNDg1OTliIl0=
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tZTIxYTgxNDYtZDMyMC01MDI5LTg5YTItNDE1YmU2YTAwOTE2Il0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDMsIm1hbHdhcmUtLTkwYTMyZTYxLTM4ZGYtNTE1MC05M2RkLTUyYjY3M2Y2MjI5YSJd
Fetched entities: 2839
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMzA1LCJtYWx3YXJlLS1jMGFkMjkxZS00YjYxLTViMTEtOGQzZC04YjdhOGZjYjViMDkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjMzLCJtYWx3YXJlLS03MDUwZDEwZC03NTBmLTU1ZTctYWZiOS00MGU3YmYwNDBlNmMiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDY2NiwibWFsd2FyZS0tYmJiZWVlMTctNzMyYS01MzI3LWFhMTUtOWQyNmY0NTY0M2E5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzUyMzkzMiwibWFsd2FyZS0tN2U2NTU0N2ItMGNkNC01MWM1LTgyMDQtZDFlZjc1MmQxNWY2Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTA0LCJtYWx3YXJlLS1hNzkwODBiMy05NGYzLTViYzMtOTUxMy00NjdjMjQ0M2YwNzEiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDMsIm1hbHdhcmUtLTYzZjk2ZmYxLWI5MTktNWU2NS1hYjdiLWY3YWE2MjdlN2YyNCJd
Fetched entities: 3967
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMzA1LCJtYWx3YXJlLS1jMGFkMjkxZS00YjYxLTViMTEtOGQzZC04YjdhOGZjYjViMDkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjM3NCwibWFsd2FyZS0tNzA1MGQxMGQtNzUwZi01NWU3LWFmYjktNDBlN2JmMDQwZTZjIl0=
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDcwNCwibWFsd2FyZS0tYmJiZWVlMTctNzMyYS01MzI3LWFhMTUtOWQyNmY0NTY0M2E5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzMyMjQ5MywibWFsd2FyZS0tNzMwNzRkM2QtN2NlYy01M2NkLWJjM2ItYTI5NmZkYjMxNTI5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNjk3NzA1LCJtYWx3YXJlLS0yYmM2Njg3Mi1iYTZkLTU2YTktOGFkZS1mZDJlZjc0YTI1OWQiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDMsIm1hbHdhcmUtLTYzZjk2ZmYxLWI5MTktNWU2NS1hYjdiLWY3YWE2MjdlN2YyNCJd
Fetched entities: 3967
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMzA1LCJtYWx3YXJlLS1jMGFkMjkxZS00YjYxLTViMTEtOGQzZC04YjdhOGZjYjViMDkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjM3NCwibWFsd2FyZS0tNzA1MGQxMGQtNzUwZi01NWU3LWFmYjktNDBlN2JmMDQwZTZjIl0=
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTA0LCJtYWx3YXJlLS0zM2RhOGEzNi1kMmYzLTUxMmQtYTFmMi0xZGZjM2JiYmEwM2UiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNjk3NzA1LCJtYWx3YXJlLS1hNmY5ZjgwZS00OTI1LTVhZWQtODM4ZS00ZDY3Y2YwYzQ0OGYiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNjkwMDM1MywibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
Fetched entities: 3000
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuNzg0MjM3NCwibWFsd2FyZS0tYmJiZWVlMTctNzMyYS01MzI3LWFhMTUtOWQyNmY0NTY0M2E5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDcwNCwibWFsd2FyZS0tYmJiZWVlMTctNzMyYS01MzI3LWFhMTUtOWQyNmY0NTY0M2E5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTA0LCJtYWx3YXJlLS1hNzkwODBiMy05NGYzLTViYzMtOTUxMy00NjdjMjQ0M2YwNzEiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
Fetched entities: 2198
INFO:pycti.entities:Listing Malwares with filters null.
INFO:pycti.entities:Listing Malwares after WzUuODYxMzA1LCJtYWx3YXJlLS1jMGFkMjkxZS00YjYxLTViMTEtOGQzZC04YjdhOGZjYjViMDkiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNzU5MDcwNCwibWFsd2FyZS0tYmJiZWVlMTctNzMyYS01MzI3LWFhMTUtOWQyNmY0NTY0M2E5Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzUyMzkzMiwibWFsd2FyZS0tN2U2NTU0N2ItMGNkNC01MWM1LTgyMDQtZDFlZjc1MmQxNWY2Il0=
INFO:pycti.entities:Listing Malwares after WzUuNzE0MTA0LCJtYWx3YXJlLS1hNzkwODBiMy05NGYzLTViYzMtOTUxMy00NjdjMjQ0M2YwNzEiXQ==
INFO:pycti.entities:Listing Malwares after WzUuNTYwMDgyNCwibWFsd2FyZS0tYjk5ZTYwOTMtNzhjMy01NThhLTk1ZjQtYjMxYjVkZDhjNWYwIl0=
INFO:pycti.entities:Listing Malwares after WzUuNTMxMDMsIm1hbHdhcmUtLWE2ZjlmODBlLTQ5MjUtNWFlZC04MzhlLTRkNjdjZjBjNDQ4ZiJd
Fetched entities: 3269
```

## Additional information
The `list()` method also seemed to fail sometimes with `ValueError` (without further error description), perhaps due to the OpenCTI API becoming unresponsive due to excessive load.

**Comment by Markus98** [comment] 2023-07-13 13:46
Upon further investigation, it was found that sometimes the function returns duplicate objects with the same `"id"` attribute. It seems that whole duplicate pages are being fetched, since the number of duplicate objects is often divisible by 500, which is the size of a page per request.

**Comment by SouadHadjiat** [comment] 2023-09-05 19:14
Hello @Markus98,
I suspect the default ordering to be an issue, could you try with a specified order ? with **orderBy** and **orderMode** : 

```
malware_entities = client.malware.list(
        customAttributes="id name aliases",
        orderBy="created_at",
        orderMode="asc",
        getAll=True,
    )
```

**Comment by Markus98** [comment] 2023-09-07 09:25
Hi @SouadHadjiat,
Rerunning the snippet with the parameters `orderBy="created_at", orderMode="asc"` seems to produce consistent results, so you may be correct about the cause of the issue.

I reran the query tens of times to test it and it always returned the same number of entities, whereas running with the default ordering still produces the inconsistent behavior.

**Comment by SamuelHassine** [comment] 2023-09-08 12:05
@SouadHadjiat Julien found the issue. You can talk with him it is a backend problem.

**Comment by richard-julien** [comment] 2023-09-08 21:38
Closing as duplicate of https://github.com/OpenCTI-Platform/opencti/issues/4287

**Closed by richard-julien** 2023-09-08 21:38 UTC
Labels: bug
