### ISSUE TITLE
Fail to execute engine pagination

### ISSUE THREAD

**Issue by aineps** [OpenCTI-Platform/client-python#743] opened 2024-10-03 13:02 UTC
## Description

When using the list functions with parameters, for example: 
```relationships = opencti_client.stix_core_relationship.list(
    filters={
        "mode": "and",
        "filters": [
            {"key": "relationship_type", "values": ["related-to"]},
            {"key": "fromTypes", "values": ["Organization", "Individual"]},
            {"key": "toTypes", "values": ["Channel"]},
        ],
        "filterGroups": [],
    },
    # getAll=True
)
```
the following error occurs: `ValueError: {'name': 'DATABASE_ERROR', 'error_message': 'Fail to execute engine pagination'}`. 

This happens with or without the getAll parameter, and with other simpler requests (for example: `opencti_client.identity.list(getAll=True)`) but not if there are no parameters at all. This error only started after updating to 6.3.1.

## Environment

OpenCTI version: 6.3.4 
pyCTI version: 6.3.4

**Comment by romain-filigran** [comment] 2024-10-16 07:24
Hello @aineps : I wasn't able to reproduce your problem with version 6.3.5 of PYCTI. This type of error is generally related to an error with elasticSearch. Can you have a look into elasticsearch logs when this error occur ?

**Comment by nino-filigran** [comment] 2024-12-03 08:21
Closing this issue since we were not able to reproduce and no movment on the ticket. Feel free to re-open it if needed!

**Closed by nino-filigran** 2024-12-03 08:21 UTC
Labels: bug, needs more info
